import { Complaint } from "@/types"

export const mockComplaints: Complaint[] = [
  {
    _id: "1",
    title: "Broken Road near Disco Bakery Gulshan",
    description:
      "Large potholes and broken asphalt making it impossible to drive safely. Multiple accidents reported near Disco Bakery on main University Road.",
    category: "Road",
    area: "Gulshan-e-Iqbal",
    status: "Pending",
    priority: "High",
    upvotes: 24,
    createdAt: "2026-08-29T10:00:00Z",
    createdBy: "Ahmed Khan",
    imageUrl: undefined,
    feedbackPending: false,
  },
  {
    _id: "2",
    title: "Garbage pile in Lyari Market",
    description:
      "Uncollected garbage for over 2 weeks near Lyari Market main road. Strong smell and mosquitoes spreading diseases in the area.",
    category: "Garbage",
    area: "Lyari",
    status: "In Progress",
    priority: "Medium",
    upvotes: 18,
    createdAt: "2026-08-25T08:30:00Z",
    createdBy: "Fatima Ali",
    imageUrl: undefined,
    officerRemark: "Cleaning crew dispatched on 30th Aug.",
    feedbackPending: false,
  },
  {
    _id: "3",
    title: "Water leakage in Clifton Block 2",
    description:
      "Burst water pipe causing waterlogging in Clifton Block 2 near Khayaban-e-Shahbaz. Water pressure is extremely low in surrounding houses.",
    category: "Water",
    area: "Clifton",
    status: "In Progress",
    priority: "Critical",
    upvotes: 45,
    createdAt: "2026-08-27T14:15:00Z",
    createdBy: "Hassan Raza",
    imageUrl: undefined,
    officerRemark: "KWSB team investigating. Pipe replacement scheduled.",
    feedbackPending: false,
  },
  {
    _id: "4",
    title: "Frequent electricity outages in Korangi",
    description:
      "Daily power outages lasting 4-5 hours in Korangi Sector 30. Peak summer hours are worst affected. K-Electric not responding to complaints.",
    category: "Electricity",
    area: "Korangi",
    status: "Pending",
    priority: "High",
    upvotes: 31,
    createdAt: "2026-08-26T11:00:00Z",
    createdBy: "Zainab Malik",
    imageUrl: undefined,
    feedbackPending: false,
  },
  {
    _id: "5",
    title: "Street light not working in Saddar",
    description:
      "Multiple street lights on main Saddar road near Empress Market are not working. Creates safety hazard at night.",
    category: "Electricity",
    area: "Saddar",
    status: "Resolved",
    priority: "Medium",
    upvotes: 12,
    createdAt: "2026-08-20T09:00:00Z",
    createdBy: "Usman Sheikh",
    imageUrl: undefined,
    officerRemark: "All faulty street lights repaired on 28th Aug.",
    feedbackPending: true,
    feedbackRating: 0,
  },
  {
    _id: "6",
    title: "Sewage overflow in Nazimabad",
    description:
      "Sewage water overflowing on main road of Nazimabad Block 5 near the mosque. Dangerous health hazard for residents.",
    category: "Water",
    area: "Nazimabad",
    status: "Pending",
    priority: "Critical",
    upvotes: 56,
    createdAt: "2026-08-28T07:00:00Z",
    createdBy: "Ali Raza",
    imageUrl: undefined,
    feedbackPending: false,
  },
  {
    _id: "7",
    title: "Potholes on Shahrah-e-Faisal",
    description:
      "Large potholes on Shahrah-e-Faisal near Baloch Colony causing traffic jams and vehicle damage.",
    category: "Road",
    area: "Gulshan-e-Iqbal",
    status: "In Progress",
    priority: "High",
    upvotes: 38,
    createdAt: "2026-08-24T16:00:00Z",
    createdBy: "Sara Ahmed",
    imageUrl: undefined,
    officerRemark: "Road patch work started. Expected completion: 2nd Sept.",
    feedbackPending: false,
  },
  {
    _id: "8",
    title: "Garbage burning in Lyari",
    description:
      "Residents burning garbage openly in Lyari lanes causing air pollution and respiratory issues.",
    category: "Garbage",
    area: "Lyari",
    status: "Pending",
    priority: "Medium",
    upvotes: 9,
    createdAt: "2026-08-27T12:00:00Z",
    createdBy: "Kamran Ali",
    imageUrl: undefined,
    feedbackPending: false,
  },
  {
    _id: "9",
    title: "Water shortage in Clifton",
    description:
      "No water supply for 3 days in Clifton Phase 5 and 6. KWSB giving no explanation to residents.",
    category: "Water",
    area: "Clifton",
    status: "Pending",
    priority: "Critical",
    upvotes: 67,
    createdAt: "2026-08-28T06:00:00Z",
    createdBy: "Dania Sheikh",
    imageUrl: undefined,
    feedbackPending: false,
  },
  {
    _id: "10",
    title: "Fallen electricity pole in Korangi",
    description:
      "Electricity pole fallen near Korangi Crossing 4 blocking half the road and posing danger to pedestrians.",
    category: "Electricity",
    area: "Korangi",
    status: "Resolved",
    priority: "High",
    upvotes: 22,
    createdAt: "2026-08-22T10:00:00Z",
    createdBy: "Bilal Ahmed",
    imageUrl: undefined,
    officerRemark: "Pole removed and replaced on 26th Aug.",
    feedbackPending: true,
    feedbackRating: 0,
  },
  {
    _id: "11",
    title: "Broken footpath in Saddar",
    description:
      "Footpath tiles broken and missing near Regal Chowk Saddar. Pedestrians forced to walk on busy road.",
    category: "Road",
    area: "Saddar",
    status: "In Progress",
    priority: "Low",
    upvotes: 7,
    createdAt: "2026-08-25T13:00:00Z",
    createdBy: "Ayesha Khan",
    imageUrl: undefined,
    officerRemark: "Footpath repair work ongoing.",
    feedbackPending: false,
  },
  {
    _id: "12",
    title: "Drainage blockage in Nazimabad",
    description:
      "Storm drains blocked in Nazimabad Block 4 causing waterlogging after light rain.",
    category: "Water",
    area: "Nazimabad",
    status: "Pending",
    priority: "Medium",
    upvotes: 15,
    createdAt: "2026-08-26T09:00:00Z",
    createdBy: "Imran Malik",
    imageUrl: undefined,
    feedbackPending: false,
  },
  {
    _id: "13",
    title: "Street lights off in Gulshan",
    description:
      "Street lights off for a week in Gulshan-e-Iqbal Block 1 near the park. Safety concern for evening walkers.",
    category: "Electricity",
    area: "Gulshan-e-Iqbal",
    status: "Resolved",
    priority: "Low",
    upvotes: 5,
    createdAt: "2026-08-21T18:00:00Z",
    createdBy: "Rabia Zafar",
    imageUrl: undefined,
    officerRemark: "Lights restored on 24th Aug.",
    feedbackPending: false,
  },
  {
    _id: "14",
    title: "Illegal dumping in Korangi",
    description:
      "Construction debris dumped illegally on main road in Korangi Sector 25. Blocking one lane.",
    category: "Garbage",
    area: "Korangi",
    status: "Pending",
    priority: "Medium",
    upvotes: 11,
    createdAt: "2026-08-27T15:00:00Z",
    createdBy: "Nadia Hassan",
    imageUrl: undefined,
    feedbackPending: false,
  },
  {
    _id: "15",
    title: "Traffic signal malfunction in Saddar",
    description:
      "Traffic signal at intersection of Saddar and Shahrah-e-Quaideen not working causing traffic chaos during peak hours.",
    category: "Road",
    area: "Saddar",
    status: "In Progress",
    priority: "High",
    upvotes: 29,
    createdAt: "2026-08-23T11:00:00Z",
    createdBy: "Omer Farooq",
    imageUrl: undefined,
    officerRemark: "Traffic police deployed manually. Repair team awaited.",
    feedbackPending: false,
  },
]

export function getComplaintById(id: string): Complaint | undefined {
  return mockComplaints.find((c) => c._id === id)
}
